### ISSUE TITLE
TypeError: 'NoneType'

### ISSUE THREAD

**Issue by TatakaRuhito** [Jertzukka/dlensExporter#7]
When I start the exporter it stops after my first 11 cards (out of 1711). In the command line it says the following:

> Preparing files, this might take a bit...
> Traceback (most recent call last):
>   File "main.py", line 241, in startexport
>   File "main.py", line 196, in getcarddatabyid
> TypeError: 'NoneType' object is not subscriptable

How can I fix this?

It stops scanning after it has scanned 2 of my Jumstart Terrarion cards. After that it should find 7 copies of Silent dart (I checked which order it scanned in by checking the order in the DelverLens app) Nothing special about the card, just 7 English Silent Dart's from Guilds of Ravnica.
I am on Windows 11, installed the latest apk and scryfall json.

**Comment by TatakaRuhito** [comment]
I deleted silent dart from my list and exported it into a new Dlens file. It has now been abled to scan 371 cards. I think it has trouble scanning cards that Delver Lens has identified as being from the Ravnica Remstared Set. While the cards are actualle from the GUilds of Ravnica set, the same art is used, so it just picks the latest set. I will now sort thorugh my Delver Lens list for al Ravnica Remstered Cards, and change them to Guilds of Ravnica.

**Comment by Jertzukka** [comment]
@TatakaRuhito Are you using version 1.2, as that had fixes on the Windows unicode formatting? If so, can you provide the .dlens file in question so I can look at it and try to reproduce?

**Comment by TatakaRuhito** [comment]
Hi,

I found out it's just Cards labbeled to be from Ravnica Remastered that
produce the error. Most likely they are not included in the json, of maybe
they cause an error in the code.
I updated the Dlens file so it's now the correct set Ravnica Allegiance is
mentioned, I deleted the old one though.

Will probably be fixed when the new set is officially released and the json
is updated.
